name: Build and Upload Lambda Code

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build code
        run: npx tsc

      - name: Bundle lambda code (class-assignment)
        run: "npx esbuild dist/event-handlers/class-assignment/handleClassAssignmentEvent.js --bundle --platform=node --outfile=dist/event-handlers/class-assignment/handleClassAssignmentEventBundle.js"

      - name: Zip lambda code (class-assignment)
        run: zip -r handleClassAssignmentEvent.zip dist/event-handlers/class-assignment/handleClassAssignmentEventBundle.js node_modules/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-3

      - name: Upload to S3 (class-assignment)
        run: |
          aws s3 cp lambda-code.zip s3://${{ secrets.AWS_S3_LAMBDA_ARTIFACTS_BUCKET_NAME }}/lambda/handleClassAssignmentEvent.zip
