name: Build and Upload Lambda Code

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build Lambda code
        run: npx tsc
        run: zip -r lambda-code.zip dist/ node_modules/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-3

      - name: Upload to S3
        run: |
          aws s3 cp lambda-code.zip s3://${{ secrets.AWS_S3_BUCKET_NAME }}/lambda/handleClassAssignmentEvent.zip
