name: Build and Upload Lambda Code

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build code
        run: npx tsc

      - name: Bundle lambda code (course)
        run: "npx esbuild dist/event-handlers/course/handleCourseEvent.js --bundle --platform=node --outfile=handleCourseEvent.js"

      - name: Zip lambda code (course)
        run: zip -r handleCourseEvent.zip handleCourseEvent.js

      - name: Bundle lambda code (lesson)
        run: "npx esbuild dist/event-handlers/lesson/handleLessonEvent.js --bundle --platform=node --outfile=handleLessonEvent.js"

      - name: Zip lambda code (lesson)
        run: zip -r handleLessonEvent.zip handleLessonEvent.js

      - name: Bundle lambda code (class)
        run: "npx esbuild dist/event-handlers/class/handleClassEvent.js --bundle --platform=node --outfile=handleClassEvent.js"

      - name: Zip lambda code (class)
        run: zip -r handleClassEvent.zip handleClassEvent.js

      - name: Bundle lambda code (category)
        run: "npx esbuild dist/event-handlers/category/handleCategoryEvent.js --bundle --platform=node --outfile=handleCategoryEvent.js"

      - name: Zip lambda code (category)
        run: zip -r handleCategoryEvent.zip handleCategoryEvent.js

      - name: Bundle lambda code (enrollment and class assignment)
        run: "npx esbuild dist/event-handlers/enrollment-and-class-assignment/handleEnrollmentAndClassAssignmentEvent.js --bundle --platform=node --outfile=handleEnrollmentAndClassAssignmentEvent.js"

      - name: Zip lambda code (enrollment and class assignment)
        run: zip -r handleEnrollmentAndClassAssignmentEvent.zip handleEnrollmentAndClassAssignmentEvent.js

      - name: Bundle lambda code (tag)
        run: "npx esbuild dist/event-handlers/tag/handleTagEvent.js --bundle --platform=node --outfile=handleTagEvent.js"

      - name: Zip lambda code (tag)
        run: zip -r handleTagEvent.zip handleTagEvent.js

      - name: Bundle lambda code (scholarship)
        run: "npx esbuild dist/event-handlers/scholarship/handleScholarshipEvent.js --bundle --platform=node --outfile=handleScholarshipEvent.js"

      - name: Zip lambda code (scholarship)
        run: zip -r handleScholarshipEvent.zip handleScholarshipEvent.js

      - name: Bundle lambda code (main)
        run: "npx esbuild dist/event-handlers/main/handleMainEvent.js --bundle --platform=node --outfile=handleMainEvent.js"

      - name: Zip lambda code (main)
        run: zip -r handleMainEvent.zip handleMainEvent.js

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-3

      - name: Deploy lambda code (course)
        run: |
          aws lambda update-function-code \
              --function-name COURSE_LAMBDA \
              --zip-file fileb://handleCourseEvent.zip \
              --publish

      - name: Deploy lambda code (lesson)
        run: |
          aws lambda update-function-code \
              --function-name LESSON_LAMBDA \
              --zip-file fileb://handleLessonEvent.zip \
              --publish

      - name: Deploy lambda code (class)
        run: |
          aws lambda update-function-code \
              --function-name CLASS_LAMBDA \
              --zip-file fileb://handleClassEvent.zip \
              --publish

      - name: Deploy lambda code (category)
        run: |
          aws lambda update-function-code \
              --function-name CATEGORY_LAMBDA \
              --zip-file fileb://handleCategoryEvent.zip \
              --publish

      - name: Deploy lambda code (enrollment and class assignment)
        run: |
          aws lambda update-function-code \
              --function-name ENROLLMENT_AND_CLASS_ASSIGNMENT_LAMBDA \
              --zip-file fileb://handleEnrollmentAndClassAssignmentEvent.zip \
              --publish

      - name: Deploy lambda code (tag)
        run: |
          aws lambda update-function-code \
              --function-name TAG_LAMBDA \
              --zip-file fileb://handleTagEvent.zip \
              --publish

      - name: Deploy lambda code (scholarship)
        run: |
          aws lambda update-function-code \
              --function-name SCHOLARSHIP_LAMBDA \
              --zip-file fileb://handleScholarshipEvent.zip \
              --publish

      - name: Deploy lambda code (main)
        run: |
          aws lambda update-function-code \
              --function-name MAIN_LAMBDA \
              --zip-file fileb://handleMainEvent.zip \
              --publish